import { Testimonial, Metric, ConsultingBrand, ProcessPhase, CaseStudy, FAQ } from '@/types';
export const testimonials: Testimonial[] = [
  {
    id: '1',
    client: 'Sarah Chen',
    role: 'CEO',
    company: 'TechFlow Solutions',
    content: 'Velorian transformed our customer service with an AI chatbot that handles 80% of inquiries autonomously. The 30-day deployment was flawless.',
    result: 'Reduced support costs by $180K annually while improving response times by 90%',
    moneySaved: 180000,
    efficiencyGain: 90,
    category: 'B2B',
    industry: 'SaaS',
    projectType: '30days',
  },
  {
    id: '2',
    client: 'Marcus Rodriguez',
    role: 'COO',
    company: 'RetailEdge',
    content: 'Within 60 days, Velorian built us a predictive inventory system that eliminated stockouts and reduced overstock by 65%. Our margins improved immediately.',
    result: 'Saved $420K in inventory costs and increased revenue by $1.2M in Q1',
    moneySaved: 420000,
    revenueIncrease: 1200000,
    category: 'B2C',
    industry: 'Retail',
    projectType: '60days',
  },
  {
    id: '3',
    client: 'Dr. Aisha Patel',
    role: 'Director of Operations',
    company: 'MedCare Plus',
    content: 'The AI-powered patient scheduling system Velorian deployed reduced no-shows by 45% and freed up our staff to focus on patient care instead of administrative tasks.',
    result: 'Increased patient throughput by 30% and saved 15 hours of admin time daily',
    efficiencyGain: 45,
    moneySaved: 250000,
    category: 'B2B',
    industry: 'Healthcare',
    projectType: '30days',
  },
  {
    id: '4',
    client: 'James Wu',
    role: 'VP Marketing',
    company: 'GrowthCo',
    content: 'Velorian\'s AI content generation and optimization platform helped us scale our content production 10x while maintaining quality. Our organic traffic grew 300%.',
    result: 'Generated $800K in additional revenue from organic channels',
    revenueIncrease: 800000,
    efficiencyGain: 1000,
    category: 'B2B',
    industry: 'Marketing',
    projectType: '60days',
  },
  {
    id: '5',
    client: 'Emily Thompson',
    role: 'Founder',
    company: 'StyleHub',
    content: 'The personalized product recommendation engine Velorian built increased our average order value by 35% and conversion rate by 28%. ROI was immediate.',
    result: 'Added $2.1M in annual revenue with 28% conversion lift',
    revenueIncrease: 2100000,
    category: 'B2C',
    industry: 'E-commerce',
    projectType: '30days',
  },
  {
    id: '6',
    client: 'Robert Kim',
    role: 'CFO',
    company: 'FinanceFirst',
    content: 'Velorian automated our invoice processing and expense management. What used to take 3 days now happens in minutes. The accuracy is perfect.',
    result: 'Saved 120 hours monthly and reduced processing errors to zero',
    moneySaved: 95000,
    efficiencyGain: 95,
    category: 'B2B',
    industry: 'Finance',
    projectType: '60days',
  },
];
export const metrics: Metric[] = [
  {
    label: 'Total Savings Generated',
    value: '$5.2M+',
    subtext: 'For our clients in 2024',
    icon: 'DollarSign',
  },
  {
    label: 'Revenue Increase',
    value: '$12.8M+',
    subtext: 'Through AI-driven growth',
    icon: 'TrendingUp',
  },
  {
    label: 'Efficiency Gains',
    value: '847%',
    subtext: 'Average improvement',
    icon: 'Zap',
  },
  {
    label: 'Deployment Speed',
    value: '30-60 Days',
    subtext: 'From concept to production',
    icon: 'Rocket',
  },
];
export const consultingBrands: ConsultingBrand[] = [
  {
    name: '30 Days to AI',
    domain: '30days2ai.com',
    tagline: 'AI Solutions Deployed in 30 Days',
    description: 'Rapid AI implementation for businesses ready to transform quickly. Perfect for focused solutions like chatbots, automation, and predictive analytics.',
    timeline: '30 days',
    color: 'primary',
  },
  {
    name: '60 Days to AI',
    domain: '60days2ai.com',
    tagline: 'Complex AI Systems in 60 Days',
    description: 'Comprehensive AI solutions for enterprises requiring custom ML models, multi-system integrations, and advanced data pipelines.',
    timeline: '60 days',
    color: 'accent',
  },
];
export const process: ProcessPhase[] = [
  {
    day: 'Days 1-5',
    title: 'Discovery & Strategy',
    activities: [
      'Deep-dive into your business processes',
      'Identify highest-impact AI opportunities',
      'Define success metrics and KPIs',
      'Create detailed implementation roadmap',
    ],
  },
  {
    day: 'Days 6-15',
    title: 'Build & Develop',
    activities: [
      'Architect the AI solution',
      'Develop and train models',
      'Integrate with existing systems',
      'Daily progress updates',
    ],
  },
  {
    day: 'Days 16-25',
    title: 'Test & Optimize',
    activities: [
      'Rigorous testing and QA',
      'Performance optimization',
      'User acceptance testing',
      'Fine-tune based on feedback',
    ],
  },
  {
    day: 'Days 26-30',
    title: 'Launch & Scale',
    activities: [
      'Production deployment',
      'Team training and handoff',
      'Monitoring setup',
      'Post-launch support plan',
    ],
  },
];
export const caseStudies: CaseStudy[] = [
  {
    company: 'TechFlow',
    industry: 'SaaS',
    timeline: '28 days',
    challenge: 'Customer support overwhelmed with 500+ daily tickets, causing 48-hour response delays.',
    solution: 'AI chatbot handling 80% of inquiries with smart escalation for complex issues.',
    result: '$180K saved annually. Response time: 48 hours → 2 minutes.',
  },
  {
    company: 'RetailEdge',
    industry: 'Retail',
    timeline: '30 days',
    challenge: 'Frequent stockouts losing $50K/month in sales with manual inventory management.',
    solution: 'Predictive inventory system with demand forecasting and auto-reorder triggers.',
    result: '65% less overstock. $420K saved. Revenue up $1.2M in Q1.',
  },
  {
    company: 'MedCare Plus',
    industry: 'Healthcare',
    timeline: '25 days',
    challenge: '45% patient no-show rate costing $250K/year in lost appointments.',
    solution: 'AI-powered scheduling with predictive no-show alerts and automated reminders.',
    result: 'No-shows down 45%. 30% more patients seen daily. 15 admin hours saved.',
  },
];
export const faqs: FAQ[] = [
  {
    question: 'Can you really deliver in 30 days?',
    answer: 'Yes. Our 30-day sprint methodology is battle-tested across 50+ projects. We focus on high-impact, production-ready solutions with a clear scope defined in the first 5 days. Complex enterprise solutions may use our 60-day timeline.',
  },
  {
    question: 'What types of AI solutions do you build?',
    answer: 'We build chatbots, automation systems, predictive analytics, recommendation engines, document processing, content generation tools, and custom ML models. If it involves AI, we can build it fast.',
  },
  {
    question: 'How much does it cost?',
    answer: 'Every project is custom-quoted based on scope and complexity. We offer transparent, fixed-price quotes after our free consultation. No hidden fees, no surprises. Most 30-day projects range from $25K-$75K with ROI typically within 3 months.',
  },
  {
    question: 'What if the project takes longer than 30 days?',
    answer: 'We guarantee our timeline. If we go over 30 days due to our fault, you don\'t pay extra. Our discovery phase ensures we scope correctly so this rarely happens. For larger projects, we recommend our 60-day timeline upfront.',
  },
  {
    question: 'Do you provide ongoing support?',
    answer: 'Absolutely. Every project includes 30 days of post-launch support. We also offer monthly maintenance plans for monitoring, optimization, and updates to keep your AI solution performing at its best.',
  },
];
