import { Testimonial, Metric, ConsultingBrand } from '@/types';
export const testimonials: Testimonial[] = [
  {
    id: '1',
    client: 'Sarah Chen',
    role: 'CEO',
    company: 'TechFlow Solutions',
    content: 'Velorian transformed our customer service with an AI chatbot that handles 80% of inquiries autonomously. The 30-day deployment was flawless.',
    result: 'Reduced support costs by $180K annually while improving response times by 90%',
    moneySaved: 180000,
    efficiencyGain: 90,
    category: 'B2B',
    industry: 'SaaS',
    projectType: '30days',
  },
  {
    id: '2',
    client: 'Marcus Rodriguez',
    role: 'COO',
    company: 'RetailEdge',
    content: 'Within 60 days, Velorian built us a predictive inventory system that eliminated stockouts and reduced overstock by 65%. Our margins improved immediately.',
    result: 'Saved $420K in inventory costs and increased revenue by $1.2M in Q1',
    moneySaved: 420000,
    revenueIncrease: 1200000,
    category: 'B2C',
    industry: 'Retail',
    projectType: '60days',
  },
  {
    id: '3',
    client: 'Dr. Aisha Patel',
    role: 'Director of Operations',
    company: 'MedCare Plus',
    content: 'The AI-powered patient scheduling system Velorian deployed reduced no-shows by 45% and freed up our staff to focus on patient care instead of administrative tasks.',
    result: 'Increased patient throughput by 30% and saved 15 hours of admin time daily',
    efficiencyGain: 45,
    moneySaved: 250000,
    category: 'B2B',
    industry: 'Healthcare',
    projectType: '30days',
  },
  {
    id: '4',
    client: 'James Wu',
    role: 'VP Marketing',
    company: 'GrowthCo',
    content: 'Velorian\'s AI content generation and optimization platform helped us scale our content production 10x while maintaining quality. Our organic traffic grew 300%.',
    result: 'Generated $800K in additional revenue from organic channels',
    revenueIncrease: 800000,
    efficiencyGain: 1000,
    category: 'B2B',
    industry: 'Marketing',
    projectType: '60days',
  },
  {
    id: '5',
    client: 'Emily Thompson',
    role: 'Founder',
    company: 'StyleHub',
    content: 'The personalized product recommendation engine Velorian built increased our average order value by 35% and conversion rate by 28%. ROI was immediate.',
    result: 'Added $2.1M in annual revenue with 28% conversion lift',
    revenueIncrease: 2100000,
    category: 'B2C',
    industry: 'E-commerce',
    projectType: '30days',
  },
  {
    id: '6',
    client: 'Robert Kim',
    role: 'CFO',
    company: 'FinanceFirst',
    content: 'Velorian automated our invoice processing and expense management. What used to take 3 days now happens in minutes. The accuracy is perfect.',
    result: 'Saved 120 hours monthly and reduced processing errors to zero',
    moneySaved: 95000,
    efficiencyGain: 95,
    category: 'B2B',
    industry: 'Finance',
    projectType: '60days',
  },
];
export const metrics: Metric[] = [
  {
    label: 'Total Savings Generated',
    value: '$5.2M+',
    subtext: 'For our clients in 2024',
    icon: 'DollarSign',
  },
  {
    label: 'Revenue Increase',
    value: '$12.8M+',
    subtext: 'Through AI-driven growth',
    icon: 'TrendingUp',
  },
  {
    label: 'Efficiency Gains',
    value: '847%',
    subtext: 'Average improvement',
    icon: 'Zap',
  },
  {
    label: 'Deployment Speed',
    value: '30-60 Days',
    subtext: 'From concept to production',
    icon: 'Rocket',
  },
];
export const consultingBrands: ConsultingBrand[] = [
  {
    name: '30 Days to AI',
    domain: '30daystoai.com',
    tagline: 'AI Solutions Deployed in 30 Days',
    description: 'Rapid AI implementation for businesses ready to transform quickly. Perfect for focused solutions like chatbots, automation, and predictive analytics.',
    timeline: '30 days',
    color: 'primary',
  },
  {
    name: '60 Days to AI',
    domain: '60days2ai.com',
    tagline: 'Complex AI Systems in 60 Days',
    description: 'Comprehensive AI solutions for enterprises requiring custom ML models, multi-system integrations, and advanced data pipelines.',
    timeline: '60 days',
    color: 'accent',
  },
];
